# Generated by Django 4.2.3 on 2023-07-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='last_updated',
            new_name='last_data_timestamp',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('down', 'Down')], max_length=20, null=True),
        ),
    ]
