# Generated by Django 4.2.3 on 2023-07-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_device_description_device_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_data_timestamp',
        ),
    ]
