# Generated by Django 4.2.3 on 2023-07-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_realtimedata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimedata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', to_field='device_id'),
        ),
    ]
