# Generated by Django 4.2.3 on 2023-07-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_remove_device_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('down', 'Down')], default=('down', 'Down'), max_length=20),
        ),
    ]
